services:
  db:
    image: postgres:16
    container_name: pub-crawl-db
    environment:
      POSTGRES_USER: crawl
      POSTGRES_PASSWORD: crawl
      POSTGRES_DB: crawl_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
