spring:
  datasource:
    url: jdbc:mysql://localhost:8889/pubcrawl_api?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  s3:
    bucket-name: pub-crawl-bucket
    region: us-east-2
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

# websiteUrl: 